In [2]:
from aocd import submit
import numpy as np
import re

In [3]:
YYYY=2021
DD=4

In [4]:
def load(filename):
    with open(filename,'r') as f:
         lines = [s.rstrip("\n")  for s in f]
    return lines #[d for d in lines]
test1 = load("test1.dat")
test1

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 ' 8  2 23  4 24',
 '21  9 14 16  7',
 ' 6 10  3 18  5',
 ' 1 12 20 15 19',
 '',
 ' 3 15  0  2 22',
 ' 9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 ' 2  0 12  3  7']

In [5]:
data_in = load("input.dat")

In [57]:
def get_env(data):
    numbers = np.array([int(n) for n in data[0].split(",")])
    boards = []
    for b in range(1, len(data), 6):
        board = []
        for row in data[b+1: b+6]:
            board.append([int(n) for n in row.split()])
        boards.append(np.array(board))
    return  numbers, boards

In [58]:
get_env(test1)

(array([ 7,  4,  9,  5, 11, 17, 23,  2,  0, 14, 21, 24, 10, 16, 13,  6, 15,
        25, 12, 22, 18, 20,  8, 19,  3, 26,  1]),
 [array([[22, 13, 17, 11,  0],
         [ 8,  2, 23,  4, 24],
         [21,  9, 14, 16,  7],
         [ 6, 10,  3, 18,  5],
         [ 1, 12, 20, 15, 19]]),
  array([[ 3, 15,  0,  2, 22],
         [ 9, 18, 13, 17,  5],
         [19,  8,  7, 25, 23],
         [20, 11, 10, 24,  4],
         [14, 21, 16, 12,  6]]),
  array([[14, 21, 17, 24,  4],
         [10, 16, 15,  9, 19],
         [18,  8, 23, 26, 20],
         [22, 11, 13,  6,  5],
         [ 2,  0, 12,  3,  7]])])

# Teil a

In [59]:
def solution_a(data):
    numbers, boards =  get_env(data)
    for n in numbers:
        for b in boards:
            x, y = np.where(b==n)
            if len(x) > 0:
                b[x[0],[y[0]]] = -1
                if -5 in b.sum(axis=0) or -5 in b.sum(axis=1):
                    return n*b[np.where( b > -1 )].sum()

In [60]:
solution_a(test1)

4512

In [46]:
submit(solution_a(data_in),part="a",day=DD, year=YYYY)

That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

# Teil b

In [52]:
def solution_b(data):
    numbers, boards =  get_env(data)
    won=[]
    scores=[]
    for n in numbers:
        for i, b in enumerate(boards):
            if i in won:
                continue
            x, y = np.where(b==n)
            if len(x) > 0:
                b[x[0],[y[0]]] = -1
                if -5 in b.sum(axis=0) or -5 in b.sum(axis=1):
                    scores.append(n*b[np.where( b > -1 )].sum())
                    won.append(i)
    return scores[-1]

In [53]:
solution_b(test1)

1924

In [54]:
submit(solution_b(data_in),part="b",day=DD, year=YYYY)

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 4! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>