In [1]:
from aocd import submit
import numpy as np
import re

In [2]:
YYYY=2021
DD=20

In [18]:
def load(filename):
    first = True
    algo = ""
    image = []
    with open(filename,'r') as f:
        for l in f:
            if l == "\n":
                first = False
                continue
            if first:
                algo += l.strip("\n")
            else:
                image.append(l.strip("\n"))
    npalgo = np.zeros((1,len(algo)), int)
    for i, p in enumerate(algo):
        if p == "#":
            npalgo[0,i] = 1

    npimage = np.zeros((len(image), len(image[0])), int)
    for i, row in enumerate(image):
        for j, p in enumerate(row):
            if p == "#":
                npimage[i, j] = 1
            
    return npalgo[0], npimage
test1 = load("test1.dat")
test1

(array([0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
        0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
        0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 

In [61]:
data_in = load("input.dat")

In [62]:
data_in

(array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
        1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 

# Teil a

In [99]:
def inout(in_image, algo, default=0, debug=False):
    new_image = np.zeros(np.array(in_image.shape)+2,int)
    dimx, dimy = new_image.shape
    if debug:
        print(new_image.shape)
    for x in range(dimx):
        for y in range(dimy):
            code = window(in_image, x-1, y-1, default)
            if debug:
                print(f"code: {code} = {algo[code]}")
            new_image[x,y] = algo[code]
    return new_image #[1:dimx-1,1:dimy-1]

def value(image, x,y, default=0, debug=False):
    """get the value at x,y, return 0 or 1"""
    dimx, dimy = image.shape
    if x < 0 or y < 0 or x >= dimx or y >= dimy:
        return default
    else:
        return image[x,y]
    
def window(image, x, y, default = 0,debug=False):
    b = ""
    b+=str(value(image,x-1,y-1, default))
    b+=str(value(image,x-1,y, default))
    b+=str(value(image,x-1,y+1, default))
    b+=str(value(image,x,y-1, default))
    b+=str(value(image,x,y, default))
    b+=str(value(image,x,y+1, default))
    b+=str(value(image,x+1,y-1, default))
    b+=str(value(image,x+1,y, default))
    b+=str(value(image,x+1,y+1, default))
    if debug:
        print(b)
    return int(b, 2)
    
def solution_a(data):
    a=inout(data[1], data[0])
    print(a)
    b=inout(a, data[0], default=data[0][0])
    print(b)
    dimx, dimy = b.shape
    return b.sum() #b[2:dimx-2,2:dimy-2].sum()

In [100]:
solution_a(test1)

[[0 1 1 0 1 1 0]
 [1 0 0 1 0 1 0]
 [1 1 0 1 0 0 1]
 [1 1 1 1 0 0 1]
 [0 1 0 0 1 1 0]
 [0 0 1 1 0 0 1]
 [0 0 0 1 0 1 0]]
[[0 0 0 0 0 0 0 1 0]
 [0 1 0 0 1 0 1 0 0]
 [1 0 1 0 0 0 1 1 1]
 [1 0 0 0 1 1 0 1 0]
 [1 0 0 0 0 0 1 0 1]
 [0 1 0 1 1 1 1 1 0]
 [0 0 1 0 1 1 1 1 1]
 [0 0 0 1 1 0 1 1 0]
 [0 0 0 0 1 1 1 0 0]]


35

In [101]:
solution_a(data_in)

[[1 0 0 ... 1 1 1]
 [1 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 0]
 ...
 [1 0 1 ... 1 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]]
[[0 1 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]
 [1 0 0 ... 0 1 1]
 ...
 [1 1 1 ... 1 0 0]
 [1 1 0 ... 1 1 0]
 [1 0 0 ... 0 0 0]]


5400

In [102]:
submit(solution_a(data_in),part="a",day=DD, year=YYYY)

[[1 0 0 ... 1 1 1]
 [1 0 0 ... 0 0 1]
 [0 1 0 ... 0 0 0]
 ...
 [1 0 1 ... 1 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]]
[[0 1 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]
 [1 0 0 ... 0 1 1]
 ...
 [1 1 1 ... 1 0 0]
 [1 1 0 ... 1 1 0]
 [1 0 0 ... 0 0 0]]
That's the right answer!  You are one gold star closer to finding the sleigh keys. [Continue to Part Two]


<Response [200]>

# Teil b

In [111]:
def solution_b(data):
    image = np.array(data[1], copy=True)
    algo = data[0]
    for i in range(50):
        if i%2:
            default = algo[0]
        else:
            default=0
        image = inout(image, algo, default)
    return image.sum() #b[2:dimx-2,2:dimy-2].sum()

In [112]:
solution_b(data_in)

18989

In [113]:
submit(solution_b(data_in),part="b",day=DD, year=YYYY)

That's the right answer!  You are one gold star closer to finding the sleigh keys.You have completed Day 20! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


<Response [200]>